# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'powerPad_ui.ui'
#
# --------------------------------------------------------------- #
#       Copyright 2021, Abanob Ashraf, All rights reserved.       #
# --------------------------------------------------------------- #
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 650)
        MainWindow.setStyleSheet("/* Colors */\n"
"\n"
"/* rgb(225,224,225); /* veryLight */\n"
"/* rgb(200,199,200); /* lighter */\n"
"/* rgb(122,121,122); /* light */\n"
"/* rgb(88,87,88); /* kindaDark */\n"
"/* rgb(60, 63, 65); /* dark */\n"
"/* rgb(31,30,31); /* veryDark */\n"
"/* rgb(11,10,11); /* veryVeryDark */\n"
"/* rgb(42,130,218); /* blue */\n"
"\n"
"\n"
"/* General style, we override only what is needed. */\n"
"QWidget {\n"
"    background-color: rgb(60, 63, 65); /* dark */\n"
"    alternate-background-color: rgb(31,30,31); /* veryDark */\n"
"    color: rgb(225,224,225); /* veryLight */\n"
"    selection-background-color: rgb(42,130,218); /* blue */\n"
"    selection-color: black;\n"
"}\n"
"\n"
"* [frameShape=\"1\"], * [frameShape=\"2\"], * [frameShape=\"3\"], * [frameShape=\"4\"], * [frameShape=\"5\"], * [frameShape=\"6\"] {\n"
"    border: 1px solid rgb(31,30,31);\n"
"}\n"
"\n"
"\n"
"/* Misc */\n"
"\n"
"QWidget::disabled {\n"
"    color: 2px solid rgb(200,199,200); /* lighter */\n"
"}\n"
"\n"
"QAbstractItemView {\n"
"    background-color: rgb(31,30,31); /* veryDark */\n"
"}\n"
"\n"
"QToolTip {\n"
"    background-color: rgb(31,30,31); /* veryDark */\n"
"    color: rgb(205,205,205);\n"
"    border: none;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background-color: rgb(60, 63, 65); /* dark */\n"
"}\n"
"\n"
"QListWidget::item:selected:!active {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(48,47,48);\n"
"}\n"
"\n"
"\n"
"/* Group Box */\n"
"\n"
"QGroupBox {\n"
"    border: 1px solid rgb(31,30,31); /* veryDark */;\n"
"    border-radius: 5px;\n"
"    padding-top: 16px;\n"
"}\n"
"\n"
"\n"
"/* ScrollBars */\n"
"\n"
"::corner {\n"
"    background-color:rgb(60, 63, 65); /* dark */\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background-color: QLinearGradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 rgb(31,30,31), /* veryDark */\n"
"        stop: 0.75 rgb(54, 53, 54),\n"
"        stop: 1 rgb(60, 63, 65)); /* dark */\n"
"    width: 14px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: QLinearGradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 rgb(122,121,122), /* light */\n"
"        stop: 0.25 rgb(100, 99, 100),\n"
"        stop: 1 rgb(88,87,88)); /* kindaDark */\n"
"    min-height: 20px;\n"
"    margin: 2px;\n"
"    border-radius: 5px;\n"
"    border-width: 1px;\n"
"    border: 1px solid rgb(31,30,31); /* veryDark */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical, QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"    color: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    background-color: QLinearGradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 rgb(31,30,31), /* veryDark */\n"
"        stop: 0.75 rgb(54, 53, 54),\n"
"        stop: 1 rgb(60, 63, 65)); /* dark */\n"
"    width: 14px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: QLinearGradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 rgb(122,121,122), /* light */\n"
"        stop: 0.25 rgb(100, 99, 100),\n"
"        stop: 1 rgb(88,87,88)); /* kindaDark */\n"
"    min-height: 20px;\n"
"    margin: 2px;\n"
"    border-radius: 5px;\n"
"    border-width: 1px;\n"
"    border: 1px solid rgb(31,30,31); /* veryDark */\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal, QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    border: none;\n"
"    background: none;\n"
"    color: none;\n"
"}\n"
"\n"
"\n"
"/* Scenes and Sources toolbar */\n"
"\n"
"QToolBar {\n"
"    background-color:rgb(60, 63, 65); /* dark */\n"
"    border:1px solid rgb(255, 255, 255,.1);\n"
"    border-right:none;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(122,121,122); /* light */\n"
"    border-radius: none;\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: rgb(9, 79, 230,.1); /* veryDark */\n"
"    border-radius: none;\n"
"}\n"
"\n"
"* [themeID=\"addIconSmall\"] {\n"
"    qproperty-icon: url(./Dark/plus.png);\n"
"}\n"
"\n"
"* [themeID=\"removeIconSmall\"] {\n"
"    qproperty-icon: url(./Dark/minus.png);\n"
"}\n"
"\n"
"* [themeID=\"propertiesIconSmall\"] {\n"
"    qproperty-icon: url(./Dark/cogwheel.png);\n"
"}\n"
"\n"
"* [themeID=\"configIconSmall\"] {\n"
"    qproperty-icon: url(./Dark/cogwheel.png);\n"
"}\n"
"\n"
"* [themeID=\"upArrowIconSmall\"] {\n"
"    qproperty-icon: url(./Dark/up_arrow.png);\n"
"}\n"
"\n"
"* [themeID=\"downArrowIconSmall\"] {\n"
"    qproperty-icon: url(./Dark/down_arrow.png);\n"
"}\n"
"\n"
"\n"
"/* Tab Widget */\n"
"\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 1px solid rgb(31,30,31); /* veryDark */\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: rgb(88,87,88); /* kindaDark */\n"
"    border: none;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    min-width: 8ex;\n"
"    padding-top: 4px;\n"
"    padding-bottom: 4px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    margin-right: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: rgb(31,30,31); /* veryDark */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: rgb(122,121,122); /* light */\n"
"}\n"
"\n"
"QTabBar::tab:pressed {\n"
"    background-color: rgb(31,30,31); /* veryDark */\n"
"}\n"
"\n"
"\n"
"/* ComboBox */\n"
"\n"
"QComboBox {\n"
"    background-color: QLinearGradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 rgb(86,85,86),\n"
"        stop: 0.1 rgb(82,81,82),\n"
"        stop: 0.5 rgb(78,77,78),\n"
"        stop: 0.9 rgb(74,73,74),\n"
"        stop: 1 rgb(70,69,70));\n"
"    border-style: solid;\n"
"    border: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: rgb(31,30,31); /* veryDark */\n"
"    padding: 2px;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border:none;\n"
"    border-left: 1px solid rgba(31,30,31,155); /* veryDark */\n"
"    width: 20px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    qproperty-alignment: AlignTop;\n"
"    image: url(./Dark/updown.png);\n"
"    width: 100%;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    background-color: rgb(31,30,31); /* veryDark */\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"}\n"
"\n"
"QComboBox::drop-down:editable {\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:editable {\n"
"    qproperty-alignment: AlignTop;\n"
"    image: url(./Dark/down_arrow.png);\n"
"    width: 8%;\n"
"}\n"
"\n"
"\n"
"/* Textedits etc */\n"
"\n"
"QLineEdit, QTextEdit, QPlainTextEdit {\n"
"    background-color:rgb(43, 43, 43); /* veryDark */\n"
"    border: none;\n"
"    padding-left: 2px;\n"
"}\n"
"\n"
"\n"
"/* Spinbox and doubleSpinbox */\n"
"\n"
"QSpinBox, QDoubleSpinBox {\n"
"    background-color:rgb(43, 43, 43); /* veryDark */\n"
"    border: none;\n"
"    padding-left: 2px;\n"
"    padding-right: 15px;\n"
"    margin-right: 10px;\n"
"}\n"
"\n"
"QSpinBox::up-button, QDoubleSpinBox::up-button {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top right; /* position at the top right corner */\n"
"\n"
"    background-color: rgb(88,87,88); /* kindaDark */\n"
"    border: 1px solidrgb(43, 43, 43); /* veryDark */\n"
"    border-radius: 3px;\n"
"    border-width: 0;\n"
"    border-bottom-left-radius: 0;\n"
"    border-bottom-right-radius: 0;\n"
"    border-bottom-width: 0;\n"
"}\n"
"\n"
"QSpinBox::down-button, QDoubleSpinBox::down-button {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: bottom right; /* position at the top right corner */\n"
"    background-color: rgb(88,87,88); /* kindaDark */\n"
"    border: 1px solidrgb(43, 43, 43); /* veryDark */\n"
"    border-radius: 3px;\n"
"    border-width: 0;\n"
"    border-top-left-radius: 0;\n"
"    border-top-right-radius: 0;\n"
"    border-top-width: 0;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover, QSpinBox::down-button:hover, QDoubleSpinBox::up-button:hover, QDoubleSpinBox::down-button:hover {\n"
"    background-color: rgb(122,121,122); /* light */\n"
"}\n"
"\n"
"QSpinBox::up-button:pressed, QSpinBox::down-button:pressed, QDoubleSpinBox::up-button:pressed, QDoubleSpinBox::down-button:pressed {\n"
"    background-color: rgb(60, 63, 65); /* dark */\n"
"}\n"
"\n"
"QSpinBox::up-button:disabled, QSpinBox::up-button:off, QSpinBox::down-button:disabled, QSpinBox::down-button:off {\n"
"    background-color: rgb(60, 63, 65); /* dark */\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button:disabled, QDoubleSpinBox::up-button:off, QDoubleSpinBox::down-button:disabled, QDoubleSpinBox::down-button:off {\n"
"    background-color: rgb(60, 63, 65); /* dark */\n"
"}\n"
"\n"
"QSpinBox::up-arrow, QDoubleSpinBox::up-arrow {\n"
"    image: url(./Dark/up_arrow.png);\n"
"    width: 100%;\n"
"}\n"
"\n"
"QSpinBox::down-arrow, QDoubleSpinBox::down-arrow {\n"
"    image: url(./Dark/down_arrow.png);\n"
"    width: 100%;\n"
"}\n"
"\n"
"\n"
"/* Buttons */\n"
"\n"
"QPushButton {\n"
"    color: rgb(225,224,225); /* veryLight */\n"
"     background-color: rgb(122,121,122,.3); /* light */\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    padding: 4px;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"}\n"
"\n"
"QPushButton::flat {\n"
"    background-color: rgb(60, 63, 65); /* dark */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(9, 79, 230,.5); /* light */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(9, 79, 230); /* veryDark */\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgb(122,121,122); /* light */\n"
"}\n"
"\n"
"\n"
"/* Sliders */\n"
"\n"
"QSlider::groove:horizontal {\n"
"    background-color: QLinearGradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 rgb(31,30,31), /* veryDark */\n"
"        stop: 0.75 rgb(50, 49, 50));\n"
"    height: 4px;\n"
"    border: none;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color: QLinearGradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 rgb(240,239,240), /* lighter */\n"
"        stop: 0.25 rgb(200,199,200),\n"
"        stop: 1 rgb(162,161,162)); /* light */\n"
"    border: 1px solid rgb(60, 63, 65); /* dark */\n"
"    border-radius: 3px;\n"
"    height: 10px;\n"
"    width: 18px;\n"
"    margin: -3px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: QLinearGradient(x1: 0, y1: 1, x2: 0, y2: 0,\n"
"        stop: 0 rgb(240,239,240), /* lighter */\n"
"        stop: 0.25 rgb(200,199,200),\n"
"        stop: 1 rgb(162,161,162)); /* light */\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"    background-color: QLinearGradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 rgb(31,30,31), /* veryDark */\n"
"        stop: 0.75 rgb(50, 49, 50));\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    background-color: QLinearGradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 rgb(31,30,31), /* veryDark */\n"
"        stop: 0.75 rgb(50, 49, 50));\n"
"    width: 4px;\n"
"    border: none;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    background-color: QLinearGradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 rgb(240,239,240), /* lighter */\n"
"        stop: 0.25 rgb(200,199,200),\n"
"        stop: 1 rgb(162,161,162)); /* light */\n"
"    border: 1px solid rgb(60, 63, 65); /* dark */\n"
"    border-radius: 4px;\n"
"    width: 10px;\n"
"    height: 18px;\n"
"    margin: -3px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
"}\n"
"\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: QLinearGradient(x1: 1, y1: 0, x2: 0, y2: 0,\n"
"        stop: 0 rgb(240,239,240), /* lighter */\n"
"        stop: 0.25 rgb(200,199,200),\n"
"        stop: 1 rgb(162,161,162)); /* light */\n"
"}\n"
"\n"
"QSlider::sub-page:vertical:disabled {\n"
"    background-color: QLinearGradient(x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 rgb(31,30,31), /* veryDark */\n"
"        stop: 0.75 rgb(50, 49, 50));\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:hover {\n"
"    background-color: rgb(200,199,200); /* veryLight */\n"
"}\n"
"\n"
"QSlider::sub-page {\n"
"    background-color: rgb(42,130,218); /* blue */\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:disabled {\n"
"    background-color: rgb(122,121,122); /* light */\n"
"}\n"
"\n"
"\n"
"/* Volume Control */\n"
"\n"
"VolumeMeter {\n"
"    qproperty-bkColor: rgb(31,30,31); /* veryDark */\n"
"    qproperty-magColor:;\n"
"    qproperty-peakColor:;\n"
"    qproperty-peakHoldColor: rgb(225,224,225); /* veryLight */\n"
"}\n"
"\n"
"\n"
"/* Status Bar */\n"
"\n"
"QStatusBar::item {\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"/* Mute CheckBox */\n"
"\n"
"MuteCheckBox {\n"
"    outline: none;\n"
"}\n"
"\n"
"MuteCheckBox::indicator:checked {\n"
"    image: url(./Dark/mute.png);\n"
"}\n"
"\n"
"MuteCheckBox::indicator:unchecked {\n"
"    image: url(./Dark/unmute.png);\n"
"}\n"
"\n"
"OBSHotkeyLabel[hotkeyPairHover=true] {\n"
"    color: red;\n"
"}\n"
"\n"
"\n"
"/* Label warning/error */\n"
"\n"
"QLabel#warningLabel {\n"
"    color: rgb(192, 128, 0);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel#errorLabel {\n"
"    color: rgb(192, 0, 0);\n"
"    font-weight: bold;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setStyleSheet("border:none;")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mainFrame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sideBanal = QtWidgets.QFrame(self.mainFrame)
        self.sideBanal.setMinimumSize(QtCore.QSize(0, 0))
        self.sideBanal.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sideBanal.setStyleSheet("#sideBanal {\n"
"background-color:rgb(43, 43, 43);\n"
"border-right:1px solid rgb(116, 70, 255,.1);\n"
"}")
        self.sideBanal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideBanal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideBanal.setObjectName("sideBanal")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.sideBanal)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.treeView = QtWidgets.QTreeView(self.sideBanal)
        self.treeView.setMinimumSize(QtCore.QSize(0, 0))
        self.treeView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.treeView.setStyleSheet("background-color:rgb(43, 43, 43);\n"
"")
        self.treeView.setSortingEnabled(False)
        self.treeView.setAnimated(True)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(False)
        self.treeView.header().setCascadingSectionResizes(False)
        self.treeView.header().setHighlightSections(False)
        self.treeView.header().setSortIndicatorShown(False)
        self.treeView.header().setStretchLastSection(False)
        self.gridLayout_4.addWidget(self.treeView, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.sideBanal)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.sideBanal, 1, 1, 1, 1)
        self.statusbar = QtWidgets.QFrame(self.mainFrame)
        self.statusbar.setMinimumSize(QtCore.QSize(0, 25))
        self.statusbar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.statusbar.setStyleSheet("background-color: rgb(60, 63, 65)")
        self.statusbar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.statusbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statusbar.setObjectName("statusbar")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.statusbar)
        self.horizontalLayout_6.setContentsMargins(0, 0, 2, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_label_bottom = QtWidgets.QFrame(self.statusbar)
        self.frame_label_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_bottom.setObjectName("frame_label_bottom")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_label_bottom)
        self.horizontalLayout_7.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_credits = QtWidgets.QLabel(self.frame_label_bottom)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(7)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_credits.setObjectName("label_credits")
        self.horizontalLayout_7.addWidget(self.label_credits)
        self.loadingFrame = QtWidgets.QFrame(self.frame_label_bottom)
        self.loadingFrame.setMaximumSize(QtCore.QSize(165, 16777215))
        self.loadingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loadingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loadingFrame.setObjectName("loadingFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.loadingFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileNum = QtWidgets.QLabel(self.loadingFrame)
        self.fileNum.setMaximumSize(QtCore.QSize(57, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.fileNum.setFont(font)
        self.fileNum.setStyleSheet("color: rgb(98, 103, 111);")
        self.fileNum.setTextFormat(QtCore.Qt.AutoText)
        self.fileNum.setScaledContents(False)
        self.fileNum.setAlignment(QtCore.Qt.AlignCenter)
        self.fileNum.setWordWrap(False)
        self.fileNum.setObjectName("fileNum")
        self.horizontalLayout.addWidget(self.fileNum)
        self.progressBar = QtWidgets.QProgressBar(self.loadingFrame)
        self.progressBar.setEnabled(True)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 5))
        self.progressBar.setMaximumSize(QtCore.QSize(100, 7))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color:rgb(68, 66, 68,.5);\n"
"    min-height: 3px;\n"
"    max-height: 5px;\n"
"    border: 1px solid rgb(27, 26, 27,.7);\n"
"    border-radius: 2;  \n"
" }\n"
"QProgressBar::chunk {\n"
"    border-radius: 2;\n"
"    background-color:rgb(116, 66, 159);\n"
"}")
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.horizontalLayout_7.addWidget(self.loadingFrame)
        self.label_version = QtWidgets.QLabel(self.frame_label_bottom)
        self.label_version.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_version.setFont(font)
        self.label_version.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_version.setAlignment(QtCore.Qt.AlignCenter)
        self.label_version.setObjectName("label_version")
        self.horizontalLayout_7.addWidget(self.label_version)
        self.horizontalLayout_6.addWidget(self.frame_label_bottom)
        self.gridLayout_2.addWidget(self.statusbar, 2, 0, 1, 4)
        self.textEdit = QtWidgets.QTextEdit(self.mainFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.mainFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menuBar.setTabletTracking(False)
        self.menuBar.setNativeMenuBar(True)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setTearOffEnabled(False)
        self.menuView.setSeparatorsCollapsible(False)
        self.menuView.setToolTipsVisible(False)
        self.menuView.setObjectName("menuView")
        self.menuTheme = QtWidgets.QMenu(self.menuView)
        self.menuTheme.setObjectName("menuTheme")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setSeparatorsCollapsible(False)
        self.menuAbout.setToolTipsVisible(True)
        self.menuAbout.setObjectName("menuAbout")
        self.menuFont = QtWidgets.QMenu(self.menuBar)
        self.menuFont.setObjectName("menuFont")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setStyleSheet("border-buttom:rgb(161, 255, 73);")
        self.toolBar.setMovable(False)
        self.toolBar.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar.setIconSize(QtCore.QSize(17, 17))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.textBar = QtWidgets.QToolBar(MainWindow)
        self.textBar.setStyleSheet("border:none;\n"
"")
        self.textBar.setMovable(False)
        self.textBar.setOrientation(QtCore.Qt.Vertical)
        self.textBar.setIconSize(QtCore.QSize(23, 23))
        self.textBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.textBar.setFloatable(True)
        self.textBar.setObjectName("textBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.textBar)
        self.actionOpenFile = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_file_30px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenFile.setIcon(icon)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionOpenFolder = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_opened_folder_24px_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenFolder.setIcon(icon1)
        self.actionOpenFolder.setObjectName("actionOpenFolder")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setCheckable(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_save_30px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_undo_26px_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon3)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_redo_26px_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon4)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_cut_30px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon5)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_copy_30px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon6)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_paste_50px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon7)
        self.actionPaste.setObjectName("actionPaste")
        self.actionSideBar = QtWidgets.QAction(MainWindow)
        self.actionSideBar.setObjectName("actionSideBar")
        self.actionToolBar = QtWidgets.QAction(MainWindow)
        self.actionToolBar.setObjectName("actionToolBar")
        self.actionBanal = QtWidgets.QAction(MainWindow)
        self.actionBanal.setObjectName("actionBanal")
        self.actionStyle = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_font_style_formatting_30px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStyle.setIcon(icon8)
        self.actionStyle.setObjectName("actionStyle")
        self.actionColor = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/new/norm/icons/color/icons8_Color_Wheel_48px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionColor.setIcon(icon9)
        self.actionColor.setObjectName("actionColor")
        self.actionhighlighter = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_marker_pen_30px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionhighlighter.setIcon(icon10)
        self.actionhighlighter.setObjectName("actionhighlighter")
        self.actionUnderline = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_underline_30px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUnderline.setIcon(icon11)
        self.actionUnderline.setObjectName("actionUnderline")
        self.actionLeft = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_align_left_30px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLeft.setIcon(icon12)
        self.actionLeft.setObjectName("actionLeft")
        self.actionRight = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_align_right_30px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRight.setIcon(icon13)
        self.actionRight.setObjectName("actionRight")
        self.actionCenter = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_align_center_30px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCenter.setIcon(icon14)
        self.actionCenter.setObjectName("actionCenter")
        self.actionJustify = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_align_justify_30px_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionJustify.setIcon(icon15)
        self.actionJustify.setObjectName("actionJustify")
        self.actionBold = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_bold_30px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBold.setIcon(icon16)
        self.actionBold.setObjectName("actionBold")
        self.actionItalic = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_italic_30px_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionItalic.setIcon(icon17)
        self.actionItalic.setObjectName("actionItalic")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_print_30px_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon18)
        self.actionPrint.setObjectName("actionPrint")
        self.actionExport = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_pdf_30px_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport.setIcon(icon19)
        self.actionExport.setObjectName("actionExport")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_delete_30px_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon20)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSelectAll = QtWidgets.QAction(MainWindow)
        self.actionSelectAll.setObjectName("actionSelectAll")
        self.actionDefult = QtWidgets.QAction(MainWindow)
        self.actionDefult.setCheckable(True)
        self.actionDefult.setChecked(False)
        self.actionDefult.setObjectName("actionDefult")
        self.actionDark = QtWidgets.QAction(MainWindow)
        self.actionDark.setCheckable(True)
        self.actionDark.setChecked(True)
        self.actionDark.setObjectName("actionDark")
        self.actionVScode = QtWidgets.QAction(MainWindow)
        self.actionVScode.setCheckable(True)
        self.actionVScode.setObjectName("actionVScode")
        self.actionPyChode = QtWidgets.QAction(MainWindow)
        self.actionPyChode.setCheckable(True)
        self.actionPyChode.setObjectName("actionPyChode")
        self.actionProBar = QtWidgets.QAction(MainWindow)
        self.actionProBar.setObjectName("actionProBar")
        self.actionTextBar = QtWidgets.QAction(MainWindow)
        self.actionTextBar.setObjectName("actionTextBar")
        self.actionInsertImage = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_image_file_30px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInsertImage.setIcon(icon21)
        self.actionInsertImage.setObjectName("actionInsertImage")
        self.actionZoomIn = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_zoom_in_30px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomIn.setIcon(icon22)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtWidgets.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_zoom_out_30px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomOut.setIcon(icon23)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionFind = QtWidgets.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_search_30px_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFind.setIcon(icon24)
        self.actionFind.setObjectName("actionFind")
        self.actionMenuBar = QtWidgets.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_chevron_up_30px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMenuBar.setIcon(icon25)
        self.actionMenuBar.setObjectName("actionMenuBar")
        self.actionNewFile = QtWidgets.QAction(MainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/new/light/icons/white/icons8_Add_30px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewFile.setIcon(icon26)
        self.actionNewFile.setObjectName("actionNewFile")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionNewFile)
        self.menuFile.addAction(self.actionOpenFile)
        self.menuFile.addAction(self.actionOpenFolder)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionSelectAll)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionInsertImage)
        self.menuEdit.addSeparator()
        self.menuTheme.addAction(self.actionDark)
        self.menuView.addAction(self.menuTheme.menuAction())
        self.menuView.addAction(self.actionTextBar)
        self.menuView.addAction(self.actionSideBar)
        self.menuView.addAction(self.actionToolBar)
        self.menuView.addAction(self.actionMenuBar)
        self.menuAbout.addAction(self.actionAbout)
        self.menuFont.addAction(self.actionStyle)
        self.menuFont.addAction(self.actionColor)
        self.menuFont.addAction(self.actionhighlighter)
        self.menuFont.addSeparator()
        self.menuFont.addAction(self.actionBold)
        self.menuFont.addAction(self.actionItalic)
        self.menuFont.addAction(self.actionUnderline)
        self.menuFont.addSeparator()
        self.menuFont.addAction(self.actionLeft)
        self.menuFont.addAction(self.actionCenter)
        self.menuFont.addAction(self.actionRight)
        self.menuFont.addAction(self.actionJustify)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuFont.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.actionNewFile)
        self.toolBar.addAction(self.actionOpenFile)
        self.toolBar.addAction(self.actionOpenFolder)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addAction(self.actionExport)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionInsertImage)
        self.toolBar.addAction(self.actionMenuBar)
        self.textBar.addAction(self.actionStyle)
        self.textBar.addAction(self.actionColor)
        self.textBar.addAction(self.actionhighlighter)
        self.textBar.addSeparator()
        self.textBar.addAction(self.actionBold)
        self.textBar.addAction(self.actionItalic)
        self.textBar.addAction(self.actionUnderline)
        self.textBar.addSeparator()
        self.textBar.addAction(self.actionLeft)
        self.textBar.addAction(self.actionCenter)
        self.textBar.addAction(self.actionRight)
        self.textBar.addAction(self.actionJustify)
        self.textBar.addSeparator()
        self.textBar.addAction(self.actionZoomIn)
        self.textBar.addAction(self.actionZoomOut)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Open Folder"))
        self.label_credits.setText(_translate("MainWindow", "Registered by: Abanob Ashraf"))
        self.fileNum.setText(_translate("MainWindow", "test"))
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.label_version.setText(_translate("MainWindow", "v1.0.0"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuTheme.setTitle(_translate("MainWindow", "Theme"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.menuFont.setTitle(_translate("MainWindow", "Font"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.textBar.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.actionOpenFile.setText(_translate("MainWindow", "Open File"))
        self.actionOpenFile.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpenFolder.setText(_translate("MainWindow", "Open Folder"))
        self.actionOpenFolder.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionSideBar.setText(_translate("MainWindow", "Side Bar"))
        self.actionSideBar.setShortcut(_translate("MainWindow", "F2"))
        self.actionToolBar.setText(_translate("MainWindow", "Tool Bar"))
        self.actionToolBar.setShortcut(_translate("MainWindow", "F3"))
        self.actionBanal.setText(_translate("MainWindow", "Status Bar"))
        self.actionBanal.setShortcut(_translate("MainWindow", "F4"))
        self.actionStyle.setText(_translate("MainWindow", "Style"))
        self.actionStyle.setShortcut(_translate("MainWindow", "F6"))
        self.actionColor.setText(_translate("MainWindow", "Color"))
        self.actionhighlighter.setText(_translate("MainWindow", "Text highlighter"))
        self.actionUnderline.setText(_translate("MainWindow", "Underline"))
        self.actionLeft.setText(_translate("MainWindow", "Left"))
        self.actionRight.setText(_translate("MainWindow", "Right"))
        self.actionCenter.setText(_translate("MainWindow", "Center"))
        self.actionJustify.setText(_translate("MainWindow", "Justify"))
        self.actionBold.setText(_translate("MainWindow", "Bold"))
        self.actionBold.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionItalic.setText(_translate("MainWindow", "Italic"))
        self.actionItalic.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionPrint.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionExport.setText(_translate("MainWindow", "Export PDF"))
        self.actionExport.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionSelectAll.setText(_translate("MainWindow", "Select All"))
        self.actionDefult.setText(_translate("MainWindow", "Defult"))
        self.actionDark.setText(_translate("MainWindow", "Dark"))
        self.actionVScode.setText(_translate("MainWindow", "VsCode"))
        self.actionPyChode.setText(_translate("MainWindow", "PyCode"))
        self.actionProBar.setText(_translate("MainWindow", "Proparties bar"))
        self.actionProBar.setShortcut(_translate("MainWindow", "F12"))
        self.actionTextBar.setText(_translate("MainWindow", "Text Bar"))
        self.actionTextBar.setShortcut(_translate("MainWindow", "F1"))
        self.actionInsertImage.setText(_translate("MainWindow", "Insert Image"))
        self.actionZoomIn.setText(_translate("MainWindow", "Zoom In"))
        self.actionZoomIn.setToolTip(_translate("MainWindow", "Zoom In"))
        self.actionZoomIn.setShortcut(_translate("MainWindow", "Ctrl+]"))
        self.actionZoomOut.setText(_translate("MainWindow", "Zoom Out"))
        self.actionZoomOut.setToolTip(_translate("MainWindow", "Zoom Out"))
        self.actionZoomOut.setShortcut(_translate("MainWindow", "Ctrl+["))
        self.actionFind.setText(_translate("MainWindow", "Find"))
        self.actionMenuBar.setText(_translate("MainWindow", "Menu Bar"))
        self.actionMenuBar.setShortcut(_translate("MainWindow", "F5"))
        self.actionNewFile.setText(_translate("MainWindow", "New File"))
        self.actionNewFile.setToolTip(_translate("MainWindow", "New File"))
        self.actionNewFile.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
import icons_rc
